# Generated by Django 4.2.30 on 2026-04-12 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('calorias', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calorias')),
                ('tipo', models.CharField(choices=[('cafe', 'Café da manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche', 'Lanche')], default='outros', max_length=20, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
